USE [master]
GO

/****** Object:  Database [EventTrackerDB]    Script Date: 10/14/2015 6:07:55 PM ******/
DROP DATABASE [EventTrackerDB]
GO

/****** Object:  Database [EventTrackerDB]    Script Date: 10/14/2015 6:07:55 PM ******/
CREATE DATABASE [EventTrackerDB] ON  PRIMARY 
( NAME = N'EventTrackerDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\EventTrackerDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EventTrackerDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\EventTrackerDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EventTrackerDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventTrackerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventTrackerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventTrackerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventTrackerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventTrackerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventTrackerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventTrackerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EventTrackerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EventTrackerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventTrackerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventTrackerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventTrackerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventTrackerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventTrackerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventTrackerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventTrackerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventTrackerDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EventTrackerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventTrackerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventTrackerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventTrackerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventTrackerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventTrackerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventTrackerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventTrackerDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventTrackerDB] SET  MULTI_USER 
GO

ALTER DATABASE [EventTrackerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventTrackerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventTrackerDB] SET  READ_WRITE 
GO

