USE [master]
GO

/****** Object:  Database [MenuDB]    Script Date: 10/16/2015 1:48:59 AM ******/
DROP DATABASE [MenuDB]
GO

/****** Object:  Database [MenuDB]    Script Date: 10/16/2015 1:48:59 AM ******/
CREATE DATABASE [MenuDB] ON  PRIMARY 
( NAME = N'MenuDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MenuDB.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MenuDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MenuDB_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MenuDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MenuDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MenuDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MenuDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MenuDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MenuDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MenuDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MenuDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MenuDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MenuDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MenuDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MenuDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MenuDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MenuDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MenuDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MenuDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MenuDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MenuDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MenuDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MenuDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MenuDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MenuDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MenuDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MenuDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MenuDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MenuDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MenuDB] SET  MULTI_USER 
GO

ALTER DATABASE [MenuDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MenuDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MenuDB] SET  READ_WRITE 
GO

