//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttendance
    {
        public int EventAttendanceId { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
    }
}
